name: SaveStatePlugin
version: '1.0.0'
main: com.savestate.SaveStatePlugin
api-version: '1.21'
description: A plugin for creating and loading save states in Minecraft
author: SaveStatePlugin

commands:
  createsavestate:
    description: Create a new save state
    usage: /<command> <name>
    permission: savestate.create
  loadsave:
    description: Load a save state
    usage: /<command> <name>
    permission: savestate.load
  listsavestates:
    description: List all available save states
    usage: /<command>
    permission: savestate.list
  deletesavestate:
    description: Delete a save state
    usage: /<command> <name>
    permission: savestate.delete

permissions:
  savestate.*:
    description: Gives access to all SaveState commands
    default: op
    children:
      savestate.create: true
      savestate.load: true
      savestate.list: true
      savestate.delete: true
  savestate.create:
    description: Allows creating save states
    default: op
  savestate.load:
    description: Allows loading save states
    default: op
  savestate.list:
    description: Allows listing save states
    default: op
  savestate.delete:
    description: Allows deleting save states
    default: op